import { type NextPage } from "next";
import Head from "next/head";
import { Content, Header } from "~/components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notetaker T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
    </>
  );
};

export default Home;
